### ISSUE TITLE
unable to clone directories

### ISSUE THREAD

**Issue by pzybe** [oridb/git9#17]
I was happily cloning repositories the other day but after upgrading today I came across this error:
```
term% git/clone gits://orib.dev/git9
fetching...
indexing 1712 objects: 100%
checking out repository...
drop: './drop' directory entry not found
failed to clone gits://orib.dev/git9: cleaning git9
```
https://github.com/oridb/git9/blob/1b4c50bd8f0b80875c50948e30b9b6501c71f412/clone#L89-L92
reverting back to the previous commit works for now

**Comment by oridb** [comment]
should be fixed -- was missing a update to common.rc
