### ISSUE TITLE
Add 9legacy requirements to README

### ISSUE THREAD

**Issue by fhs** [oridb/git9#4]
9legacy needs these changes from 9front:
* [rc-line-split](http://9p.io/sources/patch/rc-line-split): implement `delim{...}` syntax for rc
* [walk](http://9p.io/sources/patch/walk): port walk command to 9legacy.
* `hold` command

I'll update the list as I find more issues.

**Comment by oridb** [comment]
FYI, I tend to be much better about checking email than github issues.

Anyways, done :)
