### ISSUE TITLE
git/compat

### ISSUE THREAD

**Issue by halfwit** [oridb/git9#9]
Set up a namespace where normal git commands work

**Comment by marzhall** [comment]
You can't tell me what to do Mom

**Comment by halfwit** [comment]
@marzhall :D

**Comment by halfwit** [comment]
The proposed PR currently works fine, when issued within a git repository. Outside of a git repo, programs like go's `go get` will fail. 

E.g., 
```
# cd .; git clone -- https://github.com/halfwit/ytcli /usr/glenda/src/github.com/halfwit/ytcli
exit status: 'git 127550: no match'package github.com/halfwit/ytcli: exit status: 'git 127550: no match'
```

**Comment by oridb** [comment]
implemented
